### ISSUE TITLE
Consensus.bam lost gene-tag after completion

### ISSUE THREAD

**Issue by mhagemann86** [aristoteleo/dynast-release#14]
Hi,

I am trying out your very nice dynast pipeline (version 0.2.0) I ran into an issue with counting after creating a consensus bam file. Somehow the consensus.bam has lost the gene-tag or gene assignment after completion. Mind you the flag for gene-tag differs from your default value "GX", but I specify --gene-tag GE when running the consensus command. I checked the in and output bam files for the presence of my gene-tag (see below), plus here is the command I ran

```
dynast consensus -t 24 -g gencode.GRCm39.vM29.primary_assembly.annotation.noChr.rRNA.gtf --umi-tag UB --barcode-tag BC --gene-tag GE --strand forward --quality 27 -o dynast_consensus UMIs.bam --barcodes expected_barcodes.txt
```

```
samtools view -@ 48 UMIs.bam | grep -c 'GE:Z:ENSMUS'
1997940041

samtools view -@ 48 consensus.bam | grep -c 'GE:Z:ENSMUS'
0
```
Is this normal and one should disregard the --gene-tag for counting after consensus building, or do you have any good input as to why this might have happened?

Thanks in advance.

Best,
Michael

**Comment by Lioscro** [comment]
Hi, @mhagemann86,

The BAM output from the `consensus` command should have the gene ID placed in the `GX` tag and gene name in the `GN` tag, regardless of what tags were used as input. Would you please check if these tags are present?

**Comment by mhagemann86** [comment]
Hi,

Thanks for quick reply. Haha, indeed it seems very much like so (see below)

```
samtools view -@ 48 consensus.bam | grep -c 'GX:Z:ENSMUS'
101906759
```
Great, that solved it. Might be good to add a small snippet about it in the documentation, that tags will be changed regardless of input tag.

/Michael
