### ISSUE TITLE
dynast estimate: behavior for genes for which estimation is skipped and --reads argument

### ISSUE THREAD

**Issue by jmartinrufino** [aristoteleo/dynast-release#2]
I take the opportunity to ask a couple additional questions on dynast estimate. What is the current behavior for genes for which estimation is skipped? 

(WARNING [estimate] Estimation skipped for 19096 cell-gen
es because they have less than 16 reads. Use `--cell-gene-threshold` to change.)

Are they removed from the anndata object? Or are they kept on it but not corrected?

My other question is whether it would be possible to allow to use more than one option in the --reads argument (e.g. transcriptome and total).

Thanks for this awesome tool!!
Jorge

**Comment by Xiaojieqiu** [comment]
@jmartinrufino for your first question, they are kept but set to be 0, please see the coveats for more details : https://dynast-release.readthedocs.io/en/latest/technical_information.html#caveats

**Comment by Lioscro** [comment]
> @jmartinrufino for your first question, they are kept but set to be 0, please see the coveats for more details : https://dynast-release.readthedocs.io/en/latest/technical_information.html#caveats

This is correct. They are kept as zeros. Of course, `nan` may be clearer, but zeros were selected to take advantage of sparsity. Having a bunch of `nan`s makes the matrix less sparse.
